# Project: CodeX Saver
# Makefile created by Dev-C++ 4.9.6.0

CC   = g++.exe
WINDRES = windres.exe
RES  = 
OBJ  = Code_Main.o Code_String.o Texture_Manager.o Render_Text.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -lopengl32 -lglu32 -lglut32 -lwinmm
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/g++-3"  -I"C:/Dev-Cpp/include" 
BIN  = CodeX_Saver.exe
CFLAGS = $(INCS)  -s -O3 -mwindows

.PHONY: all all-before all-after clean clean-custom

all: all-before CodeX_Saver.exe all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(OBJ) -o "CodeX_Saver.exe" $(LIBS) $(CFLAGS)

Code_Main.o: Code_Main.cpp
	$(CC) -c Code_Main.cpp -o Code_Main.o $(CFLAGS)

Code_String.o: Code_String.cpp
	$(CC) -c Code_String.cpp -o Code_String.o $(CFLAGS)

Texture_Manager.o: Texture_Manager.cpp
	$(CC) -c Texture_Manager.cpp -o Texture_Manager.o $(CFLAGS)

Render_Text.o: Render_Text.cpp
	$(CC) -c Render_Text.cpp -o Render_Text.o $(CFLAGS)
